# Generated by Django 4.1.5 on 2023-01-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_author_alter_book_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
    ]
